[build]
command = "npm run build" # Comando para construir el proyecto
publish = "dist"          # Carpeta donde se generan los archivos estaticos
NODE_VERSION = "22.12.0"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200